### ISSUE TITLE
Como se usa?

### ISSUE THREAD

**Issue by ZackStone** [calendulish/Pasteall#2]

**Comment by calendulish** [comment]
As instruções estão no README.md. Qual é exatamente a dificuldade?

**Comment by ZackStone** [comment]
Eu dei uma lida e percebi que não se adequaria ao meu uso. Pelo que entendi, o software apenas deixa o último conteúdo disponível após o fechamento de algum programa qualquer. Eu estou procurando um gerenciador de área de transferência em que é possível armazenar um histórico. No Windows eu usava o ClipJump, e seu diferencial é a facilidade de controle pelas teclas de atalho. Migrei para o Linux Mint, já testei vários, mas infelizmente ainda não encontrei nenhum software que se encaixe.

**Comment by calendulish** [comment]
Você pode utilizar o próprio pastie. 

https://github.com/fmoralesc/pastie

**Comment by ZackStone** [comment]
Obrigado. Ainda tenho dificuldades em "instalar" e rodar esses softwares construídos em py. Se tiver alguma referência, agradeço também.
